const LOAD_IMAGE = 'LOAD_IMAGE';
const IMAGE_LOADED = 'IMAGE_LOADED';
const EDIT_FILENAME = 'EDIT_FILENAME';
const ADD_SIZE = 'ADD_SIZE';
const EDIT_SIZE = 'EDIT_SIZE';
const REMOVE_SIZE = 'REMOVE_SIZE';
const ADD_HIGH_RES = 'ADD_HIGH_RES';
const GEN_HTML = 'GEN_HTML';
const CLOSE_POPUP = 'CLOSE_POPUP';

export default {
    LOAD_IMAGE,
    IMAGE_LOADED,
    EDIT_FILENAME,
    ADD_SIZE,
    EDIT_SIZE,
    REMOVE_SIZE,
    ADD_HIGH_RES,
    GEN_HTML,
    CLOSE_POPUP
}