const LOAD_IMAGE = 'LOAD_IMAGE';
const IMAGE_LOADED = 'IMAGE_LOADED';
const EDIT_FILENAME = 'EDIT_FILENAME';
const ADD_SIZE = 'ADD_SIZE';
const EDIT_SIZE = 'EDIT_SIZE';
const REMOVE_SIZE = 'REMOVE_SIZE';
const ADD_HIGH_RES = 'ADD_HIGH_RES';
const REC_HTML = 'REC_HTML';
const CLOSE_POPUP = 'CLOSE_POPUP';
const COPY_CLIP = 'COPY_CLIP';

export default {
    LOAD_IMAGE,
    IMAGE_LOADED,
    EDIT_FILENAME,
    ADD_SIZE,
    EDIT_SIZE,
    REMOVE_SIZE,
    ADD_HIGH_RES,
    REC_HTML,
    CLOSE_POPUP,
    COPY_CLIP
}